server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bankrest?createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

logging:
  level:
    org.springdoc: DEBUG
    io.swagger.v3: DEBUG

security:
  jwtSecret: NKussWDkmYVP9fEA4y9qLawSR3tPSrtO43uVve2ybnw=
  jwtSecretExpiration: 3600000 # 1 час в миллисекундах
  jwtRefreshExpiration: 604800000 # 7 дней

service:
  security:
    unprotected: /favicon.ico,/actuator/**,/clearCache,/error,/swagger-ui.html,/swagger-ui/**,/v3/api-docs/**,/webjars/**

springdoc:
  webmvc:
    enabled: true
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true